baseURL: 'https://raeperd.github.io/'
title: raeperd.github.io
paginate: 8
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

disqusShortname: raeperd-github-io
googleAnalytics: UA-168674186-1

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

DefaultContentLanguage: korean
languages:  
  korean:
    menu:
      main:
        - name: Article
          url: /articles
          weight: 2
        - name: Note
          url: /notes
          weight: 3
        - name: Search
          url: /search
          weight: 4
        - name: Archives
          url: /archives/
          weight: 5

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: raeperd
  # author: ["Me", "You"] # multiple authors

  mainSections:
    - articles

  ShowShareButtons: true
  comments: true
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  fuseOpts:

  assets:
    disableFingerprinting: true

  # home-info mode
  homeInfoParams:
    Title: "Hello universe \U0001FA90"
    Content: Better programmer
  socialIcons:
    - name: github
      url: 'https://github.com/raeperd'
    - name: linkedin
      url: https://www.linkedin.com/in/%EB%9E%98%EC%B2%A0-%EB%B0%95-4089b8203/
    - name: email
      url: raeperd117@gmail.com
    - name: other
      url: https://www.notion.so/raeperd/raeperd-13616f5ebff2454084995161831837a9

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
