baseURL: 'https://raeperd.github.io/'
title: raeperd.github.io
paginate: 8
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

disqusShortname: raeperd-github-io
googleAnalytics: UA-168674186-1

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

DefaultContentLanguage: korean
languages:  
  korean:
    weight: 1
    title: raeperd.github.io
    homeInfoParams:
      Title: "Hello Universe \U0001FA90"
      Content: Welcome
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
        - name: Search
          url: /search
          weight: 10

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: raeperd.github.io
  description: 'ExampleSite description'
  author: raeperd
  # author: ["Me", "You"] # multiple authors

  images: ["papermod-cover.png"]

  ShowShareButtons: true
  comments: true
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  fuseOpts:

  assets:
    disableFingerprinting: true

  label:
    text: "raeperd.github.io"

  # home-info mode
  homeInfoParams:
    Title: "Hello universe \U0001F44B"
    Content: Welcome
  socialIcons:
    - name: github
      url: 'https://github.com/raeperd'
    - name: linkedin
      url: https://www.linkedin.com/in/%EB%9E%98%EC%B2%A0-%EB%B0%95-4089b8203/
    - name: email
      url: raeperd117@gmail.com
    - name: other
      url: https://www.notion.so/raeperd/raeperd-13616f5ebff2454084995161831837a9

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: raeperd.github.io
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags